run-name: build ushare docker image
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: debian
    steps:
      - name: prepare environment
        uses: actions/checkout@v4

      - name: print info
        run: |
          date '+%Y-%m-%dT%H:%M:%S'
          whoami
          echo "Tag = ${{ gitea.ref_name }}"
          pwd && ls -alsh .

      - name: build docker image
        run: docker build -t ushare:${{ gitea.ref_name }} .
